'use client';
import {useEffect,useRef,useState} from 'react';
import Link from './native-link';
import {config,markets,money} from '../lib/model';
import type {MarketId,QuoteBook} from '../lib/market-data';

const chapters=[['protocol','The architecture'],['pricing','From price to exposure'],['trading','Trading & leverage'],['vaults','Market vaults'],['markets','Supported markets'],['risks','Risk & capacity'],['token','Token & governance'],['security','Wallet & security']];

export default function ProtocolPage({quotes,onMarket}:{quotes:QuoteBook;onMarket:(id:string)=>void}){
  const [active,setActive]=useState('protocol');
  const body=useRef<HTMLElement>(null);
  useEffect(()=>{
    const sections=Array.from(body.current?.querySelectorAll<HTMLElement>('[data-chapter]')??[]);
    const fromHash=()=>{const id=location.hash.slice(1);if(chapters.some(([key])=>key===id))setActive(id);else if(id==='governance')setActive('token')};
    const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top);if(visible[0])setActive(visible[0].target.id)},{rootMargin:'-10% 0px -55% 0px',threshold:0});
    sections.forEach(section=>observer.observe(section));fromHash();window.addEventListener('hashchange',fromHash);
    return()=>{observer.disconnect();window.removeEventListener('hashchange',fromHash)};
  },[]);
  return <div className="page-wrap protocol-guide">
    <div className="protocol-intro"><span className="eyebrow">DELTAVAULT / THE PROTOCOL</span><h1>Exposure, backed<br/>by <span>clear mechanics.</span></h1><p>Trade a direction. Supply market-specific capital. Understand the limits that connect them.</p></div>
    <div className="protocol-guide-layout">
      <nav className="protocol-index" aria-label="Protocol sections"><span className="eyebrow">IN THIS GUIDE</span>{chapters.map(([id,label],i)=><a key={id} href={'#'+id} aria-current={active===id?'location':undefined} onClick={()=>setActive(id)}><span>{String(i+1).padStart(2,'0')}</span>{label}</a>)}<a className="protocol-paper" aria-label="Read the whitepaper" href="/docs">Read the whitepaper</a></nav>
      <article className="protocol-body" ref={body}>
        <section id="protocol" data-chapter tabIndex={-1} aria-labelledby="architecture-title"><span className="eyebrow">01 / THE ARCHITECTURE</span><h2 id="architecture-title">Two roles. One capital system.</h2><p>DeltaVault connects leveraged trading with separate liquidity vaults for each supported market. Traders choose their exposure; liquidity providers supply the capital behind it.</p><p>Collateral sets the position size. Market movement changes equity. Maintenance and capacity limits define how much exposure the system can carry.</p><div className="protocol-callout">Built for Robinhood Chain. DeltaVault is independent and is not a Robinhood product, endorsement, or partnership.</div></section>
        <section id="pricing" data-chapter tabIndex={-1} aria-labelledby="pricing-title"><span className="eyebrow">02 / FROM PRICE TO EXPOSURE</span><h2 id="pricing-title">Start with a visible reference.</h2><p>Spot prices, market capitalization, 24-hour volume, and price history come from CoinGecko. The workspace uses this data to calculate price sensitivity and replay recent market movement.</p><ol className="protocol-flow">{['Select a market','Read its price','Set exposure','Inspect the outcome'].map((label,i)=><li key={label}><span>0{i+1}</span>{label}</li>)}</ol><p>A 24-hour replay applies the selected market’s historical price changes to the position. A price target lets you examine a chosen percentage move. Calculations are gross of fees, funding, slippage, and execution costs.</p><Link className="text-link" href="/markets">Compare market data</Link></section>
        <section id="trading" data-chapter tabIndex={-1} aria-labelledby="trading-title"><span className="eyebrow">03 / TRADING & LEVERAGE</span><h2 id="trading-title">Choose the direction. Measure the exposure.</h2><p>Go long to take exposure to a rising price, or short to a falling price. Set collateral and leverage, then inspect notional exposure, gross profit or loss, and remaining equity before opening a position.</p><dl className="protocol-definitions"><div><dt>Collateral</dt><dd>The starting capital that absorbs changes in position value.</dd></div><div><dt>Leverage</dt><dd>Scales exposure relative to collateral, within each market’s configured limit.</dd></div><div><dt>Gross PnL</dt><dd>Notional exposure multiplied by the price move, adjusted for long or short direction.</dd></div><div><dt>Equity</dt><dd>Initial collateral plus gross PnL, measured against maintenance.</dd></div></dl><div className="protocol-equation"><span>POSITION SIZE</span><p>Notional = collateral × leverage</p></div><Link className="text-link" href="/trade">Inspect a position</Link></section>
        <section id="vaults" data-chapter tabIndex={-1} aria-labelledby="vaults-title"><span className="eyebrow">04 / MARKET VAULTS</span><h2 id="vaults-title">Keep capital close to its market.</h2><p>Each market has its own liquidity environment. This separates capital and committed exposure between ETH, BTC, and SOL, rather than pooling every market into a single vault.</p><p>Within the protocol architecture, trader gains draw on the relevant vault and trader losses contribute to it. Committed exposure reduces the capacity available for new positions and withdrawals.</p><div className="protocol-role-grid"><div><span className="eyebrow">TRADERS</span><h3>Take exposure.</h3><p>Choose direction, collateral, and leverage.</p></div><div><span className="eyebrow">LIQUIDITY PROVIDERS</span><h3>Back the market.</h3><p>Allocate capital to a specific market vault.</p></div></div><p>Vault returns depend on trader outcomes, committed liquidity, and market conditions. Capital preservation and returns are not guaranteed.</p><Link className="text-link" href="/vaults">Explore market vaults</Link></section>
        <section id="markets" data-chapter tabIndex={-1} aria-labelledby="markets-title"><span className="eyebrow">05 / SUPPORTED MARKETS</span><h2 id="markets-title">Three markets. Separate boundaries.</h2><p>Compare current USD prices and 24-hour movement alongside the workspace’s configured leverage limits. Select a market to inspect its exposure.</p><div className="protocol-markets">{markets.map(m=>{const q=quotes[m.id as MarketId];return <Link href="/trade" key={m.id} onClick={()=>onMarket(m.id)} className="protocol-market" aria-label={`Inspect ${m.name} trading`}><div><h3>{m.id}</h3><span>{m.name}</span></div><strong>{q?'$'+money(q.price):'—'}</strong><span className="protocol-change">{q?.change24h==null?'24h change unavailable':(q.change24h>0?'+':'')+q.change24h.toFixed(2)+'% / 24h'}</span><div className="protocol-market-limit"><span>Leverage limit</span><b>{m.maxLeverage}×</b></div></Link>})}</div><p className="protocol-source">Price reference: CoinGecko · Limits: DeltaVault workspace settings</p></section>
        <section id="risks" data-chapter tabIndex={-1} aria-labelledby="risks-title"><span className="eyebrow">06 / RISK & CAPACITY</span><h2 id="risks-title">Know what the position can absorb.</h2><p>Leverage amplifies gains and losses. A modest price move can consume a large share of collateral. Compare equity with maintenance, and examine how utilization changes available capacity.</p><div className="protocol-boundaries"><div><strong>25<span>%</span></strong><h3>Maintenance threshold</h3><p>The current calculator uses 25% of initial collateral as its maintenance boundary.</p></div><div><strong>80<span>%</span></strong><h3>Capacity ceiling</h3><p>The current capacity model stops adding exposure at 80% utilization.</p></div></div><div className="protocol-equation"><span>AVAILABLE CAPACITY</span><p>Capital × max(0, 80% − utilization)</p></div><p>Risk Explorer uses your capital and utilization inputs. Its outputs are projections. Liquidity provision also carries pricing, withdrawal, and smart-contract risk.</p><Link className="text-link" href="/risk">Explore the risk boundaries</Link></section>
        <section id="token" data-chapter tabIndex={-1} aria-labelledby="token-title"><span className="eyebrow">07 / TOKEN & GOVERNANCE</span><h2 id="token-title">Participation beyond a position.</h2><p>The native token’s role covers governance, ecosystem incentives, and protocol participation. Token specification, contract details, and supply information will be published alongside those mechanisms.</p><div id="governance" className="protocol-governance"><dl className="protocol-definitions"><div><dt>Governance</dt><dd>Defines protocol parameters, market limits, and the allocation of shared resources.</dd></div><div><dt>Ecosystem incentives</dt><dd>Support participation in the trading and liquidity ecosystem.</dd></div><div><dt>Treasury</dt><dd>Coordinates resource accounting and incentive design within the protocol architecture.</dd></div></dl></div><a className="text-link" href="/docs">Read the token whitepaper</a></section>
        <section id="security" data-chapter tabIndex={-1} aria-labelledby="security-title"><span className="eyebrow">08 / WALLET & SECURITY</span><h2 id="security-title">An address is only the first step.</h2><p>Browsing markets and inspecting exposure do not require a wallet. Connecting a detected wallet shares its public address; the connection itself does not request a signature, approval, deposit, or trade.</p><p>Account connection, token approval, and transaction authorization are separate actions. Review the requested permissions, contract, network, and amount in your wallet before authorizing any action.</p><div className="protocol-actions"><Link className="button" href="/markets">Explore markets</Link><a className="button ghost" href="/docs">Read the whitepaper</a></div></section>
      </article>
    </div>
  </div>;
}
